---
env_name: "{{ lookup('env', 'ENV_NAME') | default('dev', true) }}"
aws_region: "{{ lookup('env', 'AWS_REGION') | default('us-east-1', true) }}"

ansible_user: ubuntu
ansible_python_interpreter: /usr/bin/python3

image_tag: "{{ lookup('env', 'IMAGE_TAG') | default('latest', true) }}"
ecr_registry: "{{ lookup('env', 'ECR_REGISTRY') }}"
backend_image: "{{ ecr_registry }}/todo-app-{{ env_name }}-backend:{{ image_tag }}"
frontend_image: "{{ ecr_registry }}/todo-app-{{ env_name }}-frontend:{{ image_tag }}"

frontend_api_url: "{{ lookup('env', 'BASE_API_URL') | default('http://localhost:3000/api', true)}}"

postgres_image: postgres:17-alpine

db_name: todo_db
db_user: "{{ lookup('env', 'DB_USERNAME')}}"
db_pwd: "{{ lookup('env', 'DB_PASSWORD')}}"
